ALTER TABLE Students
ADD CONSTRAINT fk_student_user FOREIGN KEY (studentID) 
REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Teachers
ADD CONSTRAINT fk_teacher_user FOREIGN KEY (teacherID) 
REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE SmartBoards
ADD CONSTRAINT fk_smartboard_room FOREIGN KEY (roomID) 
REFERENCES Classrooms(roomID) ON DELETE RESTRICT ON UPDATE CASCADE;


ALTER TABLE Module
ADD CONSTRAINT fk_module_course FOREIGN KEY (courseID) 
REFERENCES Courses(courseID) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE Enrollments
ADD CONSTRAINT fk_enroll_student FOREIGN KEY (studentID) 
REFERENCES Students(studentID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Enrollments
ADD CONSTRAINT fk_enroll_course FOREIGN KEY (courseID) 
REFERENCES Courses(courseID) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE ClassSessions
ADD CONSTRAINT fk_session_room FOREIGN KEY (roomID) 
REFERENCES Classrooms(roomID) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE ClassSessions
ADD CONSTRAINT fk_session_course FOREIGN KEY (courseID) 
REFERENCES Courses(courseID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ClassSessions
ADD CONSTRAINT fk_session_slot FOREIGN KEY (slotID) 
REFERENCES TimeSlots(slotID) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE ClassSessions
ADD CONSTRAINT fk_session_teacher FOREIGN KEY (teacherID) 
REFERENCES Teachers(teacherID) ON DELETE RESTRICT ON UPDATE CASCADE;